---
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    parserOptions.ecmaVersion: true
rules:
  curly:
  - 2
  - all
  keyword-spacing:
  - 2
  - {}
  no-with: 2
  brace-style:
  - 2
  - 1tbs
  - allowSingleLine: false
  no-multi-spaces: 2
  space-unary-ops:
  - 2
  - words: true
    nonwords: false
  space-infix-ops: 2
  space-before-blocks:
  - 2
  - always
  one-var: 0
  object-curly-spacing:
  - 2
  - never
  space-in-parens:
  - 2
  - never
  no-empty:
  - 2
  - allowEmptyCatch: true
  wrap-iife: 1
  space-before-function-paren:
  - 2
  - anonymous: always
    named: never
  comma-style:
  - 2
  - last
  quotes:
  - 2
  - single
  - allowTemplateLiterals: true
  no-multi-str: 2
  no-implicit-coercion:
  - 2
  - boolean: true
    string: true
    number: true
  yoda:
  - 2
  - never
  array-bracket-spacing:
  - 2
  - never
  key-spacing:
  - 2
  - beforeColon: false
    afterColon: true
  quote-props:
  - 2
  - as-needed
  spaced-comment: 0
  eol-last: 2
  no-multiple-empty-lines: 2
  no-mixed-spaces-and-tabs: 2
  no-trailing-spaces: 2
  linebreak-style: 0
  indent:
  - 2
  - tab
  - SwitchCase: 1
    MemberExpression: 1
  semi:
  - 2
  - always
  no-extra-semi: 2
  new-cap:
  - 2
  - capIsNewExceptions:
    - Boolean
    - String
    - Number
    - Velocity
  no-delete-var: 2
  no-debugger: 2
  no-dupe-keys: 2
  no-duplicate-case: 2
  no-cond-assign: 2
  no-func-assign: 2
  no-alert: 2
  no-undef-init: 2
  valid-typeof: 2
  comma-spacing:
  - 2
  - before: false
    after: true
  arrow-spacing:
  - 2
  - before: true
    after: true
  no-console:
  - 2
  - allow:
    - warn
    - error
    - info
    - time
    - timeEnd
